# Generated by Django 4.2.3 on 2023-07-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_rename_amont_coinbaseprocess_amount'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='purchased_tools',
            field=models.ManyToManyField(blank=True, to='tools.tool'),
        ),
    ]
