# Generated by Django 4.2.3 on 2023-07-08 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('image', models.ImageField(upload_to='tools/images')),
                ('rating', models.FloatField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload_tool', models.FileField(upload_to='tools/uploads')),
                ('quantity', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('tool_sold', models.PositiveIntegerField(default=0)),
                ('coinbase_payment_id', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=250)),
                ('token_expiration', models.DateTimeField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
