# Generated by Django 4.2.3 on 2023-07-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='name',
            new_name='tool_name',
        ),
    ]
