# Generated by Django 4.2.3 on 2023-07-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_rename_name_tool_tool_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinBaseProcess',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('amont', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tool_name', models.CharField(max_length=250)),
                ('product_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Coinbase Payment',
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
