# Generated by Django 4.2.3 on 2023-07-12 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0003_coinbaseprocess_tool_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='purchased_by',
            field=models.ManyToManyField(related_name='purchased_tools', to=settings.AUTH_USER_MODEL),
        ),
    ]
