# Generated by Django 4.2.3 on 2023-07-12 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_tool_purchased_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='purchased_by',
        ),
    ]
