# Generated by Django 4.2.3 on 2023-07-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_remove_tool_purchased_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinbaseprocess',
            old_name='amont',
            new_name='amount',
        ),
    ]
